# Generated by Django 4.1.3 on 2022-11-15 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("websites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("job_type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "short_description",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("tags", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "experience_level",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "salary_range",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=20, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=255, null=True)),
                ("source", models.CharField(blank=True, max_length=20, null=True)),
                ("source_link", models.CharField(blank=True, max_length=20, null=True)),
                ("job_status", models.BooleanField(default=False)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="websites.website",
                    ),
                ),
            ],
        ),
    ]
